# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

parameters:
  php-version:
    type: string
    default: "8"

jobs:
  phpspec:
    docker:
      - image: cimg/php:<< php-version >>
    steps:
      - checkout
      - run: php --version

workflows:
  phpspec-workflow:
    jobs:
      - phpspec:
          matrix:
            parameters:
              php-version: ["7.1", "7.2"]

